package com.wonders.hms.wonder.type;

public enum HotelAmenityKind {
    WIRELESS_INTERNET,
    BREAKFAST,
    POOL_SUM_LOUNGERS,
    RESTAURANT,
    LAUNDRY_FACILITIES,
    BUSINESS_CENTER,
    AIRPORT_TRANSPORTATION,
    MASSAGE_SPA_TREATMENT,
    LUGGAGE_STORAGE,
    FITNESS_FACILITIES,
    FRONT_DESK_24,
    PARKING,

    BARBECUE_GRILL,
    COFFEE_AND_TEA_IN_COMMON_AREAS,
    CONFERENCE_SPACE,
    ELEVATOR,
    FRONT_DESK_LIMITED_HOURS,
    MEETING_ROOMS,
    MULTILIGUAL_STAFF,
    SMOKE_FREE_PROPERTY,
    TOURS_TICKET_ASSISTANCE,
    WIRED_INTERNET_FREE,
    WIRED_INTERNET_SURCHARAGE
}
